hide-cursor-when-typing = true
theme = "catppuccin-macchiato"
confirm-before-quit = false
option-as-alt = 'left'
env-vars = ["COLORTERM=truecolor", "LANG=ja_JP.UTF-8"]

[cursor]
shape = 'beam'
blinking = true
blinking-interval = 500

[editor]
program = "vi"

[window]
width = 1200
height = 800
mode = "windowed"
opacity = 0.85
blur = true
decorations = "Enabled"
macos-use-unified-titlebar = false

[title]
content = ""

[renderer]
performance = "low"
backend = "Automatic"
disable-unfocused-render = true
# level = 1
# filters = ["newpixiecrt"]

[keyboard]
use-kitty-keyboard-protocol = true
[fonts]
size = 14
[fonts.regular]
family = "Moralerspace Xenon HWNF"
style = "Normal"
[fonts.bold]
family = "Moralerspace Neon HWNF"
style = "Normal"
weight = 800
[fonts.italic]
family = "Moralerspace Argon HWNF"
style = "Italic"
[fonts.bold-italic]
family = "Moralerspace Neon HWNF"
style = "Italic"
weight = 800

[navigation]
mode = "Plain"
clickable = true
hide-if-single = false
use-current-path = false
use-split = true

[platform]
# # Microsoft Windows overwrite
windows.shell.program = "pwsh"
windows.shell.args = ["-l"]
windows.navigation.mode = "BottomTab"
# # Linux overwrite
linux.shell.program = "tmux"
linux.shell.args = ["new-session", "-c", "/var/www"]
linux.navigation.mode = "BottomTab"
