# Homebrew CLI integrations formerly generated by Home Manager.
if (( $+commands[eza] )); then
  alias eza='eza --icons auto --git'
  alias ls='eza'
  alias ll='eza -l'
  alias la='eza -a'
  alias lt='eza --tree'
  alias lla='eza -la'
fi

if (( $+commands[zoxide] )); then
  eval "$(zoxide init zsh)"
fi

if (( $+commands[yazi] )); then
  function y() {
    local tmp cwd
    tmp="$(mktemp -t 'yazi-cwd.XXXXX')"
    command yazi "$@" --cwd-file="$tmp"
    if cwd="$(<"$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
      builtin cd -- "$cwd"
    fi
    rm -f -- "$tmp"
  }
fi

if (( $+commands[lazygit] )); then
  function lg() {
    export LAZYGIT_NEW_DIR_FILE="$HOME/.cache/lazygit/newdir"
    command lazygit "$@"
    if [ -f "$LAZYGIT_NEW_DIR_FILE" ]; then
      cd "$(cat "$LAZYGIT_NEW_DIR_FILE")"
      rm -f "$LAZYGIT_NEW_DIR_FILE"
    fi
  }
fi
