# Homebrew CLI integrations formerly generated by Home Manager.
if (( $+commands[eza] )); then
  alias eza='eza --icons auto --git'
  alias ls='eza'
  alias ll='eza -l'
  alias la='eza -a'
  alias lt='eza --tree'
  alias lla='eza -la'
fi

if (( $+commands[zoxide] )); then
  zoxide_zsh_cache_dir="${XDG_CACHE_HOME:-$HOME/.cache}/zsh"
  zoxide_zsh_cache_file="$zoxide_zsh_cache_dir/zoxide.zsh"

  if [[ ! -r "$zoxide_zsh_cache_file" || "${commands[zoxide]}" -nt "$zoxide_zsh_cache_file" ]]; then
    if mkdir -p -- "$zoxide_zsh_cache_dir" 2>/dev/null; then
      zoxide_zsh_cache_tmp="$zoxide_zsh_cache_file.$$"
      if command zoxide init zsh >| "$zoxide_zsh_cache_tmp"; then
        mv -f -- "$zoxide_zsh_cache_tmp" "$zoxide_zsh_cache_file"
      else
        rm -f -- "$zoxide_zsh_cache_tmp"
      fi
    fi
  fi

  if [[ -r "$zoxide_zsh_cache_file" ]]; then
    source "$zoxide_zsh_cache_file"
  else
    eval "$(command zoxide init zsh)"
  fi

  unset zoxide_zsh_cache_dir zoxide_zsh_cache_file zoxide_zsh_cache_tmp
fi

if (( $+commands[yazi] )); then
  function y() {
    local tmp cwd
    tmp="$(mktemp -t 'yazi-cwd.XXXXX')"
    command yazi "$@" --cwd-file="$tmp"
    if cwd="$(<"$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
      builtin cd -- "$cwd"
    fi
    rm -f -- "$tmp"
  }
fi

if (( $+commands[lazygit] )); then
  function lg() {
    export LAZYGIT_NEW_DIR_FILE="$HOME/.cache/lazygit/newdir"
    command lazygit "$@"
    if [ -f "$LAZYGIT_NEW_DIR_FILE" ]; then
      cd "$(cat "$LAZYGIT_NEW_DIR_FILE")"
      rm -f "$LAZYGIT_NEW_DIR_FILE"
    fi
  }
fi
