profiles:
- id: DED4BAEB-AB62-4FF4-BD2F-91D6B89F6E43
  name: Default
  workspaces:
  - id: 797F6AA2-BADC-45D8-94C1-6DE5D9509A6F
    name: Home
    display: Built-in Retina Display
    apps:
    - name: Vivaldi
      bundleIdentifier: com.vivaldi.Vivaldi
      iconPath: /Applications/Vivaldi.app/Contents/Resources/app.icns
    symbolIconName: house.fill
  - id: D60D542A-B84A-4852-A89D-4C4CC5312283
    name: Programing
    display: LG HDR 4K
    apps:
    - name: CodeRunner
      bundleIdentifier: com.krill.CodeRunner
      iconPath: /Applications/CodeRunner.app/Contents/Resources/CodeRunner.icns
    - name: Firefox Developer Edition
      bundleIdentifier: org.mozilla.firefoxdeveloperedition
      iconPath: /Applications/Firefox Developer Edition.app/Contents/Resources/firefox.icns
    - name: Vivaldi
      bundleIdentifier: com.vivaldi.Vivaldi
      iconPath: /Applications/Vivaldi.app/Contents/Resources/app.icns
    - name: Zed
      bundleIdentifier: dev.zed.Zed
      iconPath: /Applications/Zed.app/Contents/Resources/Zed.icns
    - name: VSCodium
      bundleIdentifier: com.vscodium
      iconPath: /Applications/VSCodium.app/Contents/Resources/VSCodium.icns
    symbolIconName: apple.terminal.on.rectangle.fill
  - id: D33180D1-223D-4544-8C19-88B89858102E
    name: University
    display: Built-in Retina Display
    apps:
    - name: Google Chrome
      bundleIdentifier: com.google.Chrome
      iconPath: /Applications/Google Chrome.app/Contents/Resources/app.icns
