"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$directory\
$git_branch\
$fill $git_status
$character
"""

right_format = """
$time
"""

command_timeout = 100

continuation_prompt = " ❯❯ "

palette = "catppuccin_macchiato"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"

[fill]
symbol = ' '
style = 'subtext0'

[character]
format = "$symbol"
success_symbol = "[[󰄛](sky) ❯ ](sapphire)"
error_symbol = "[[󰄛](red) ❯ ](peach)"
vimcmd_symbol = "[󰄛 ❮ ](subtext1)" # For use with zsh-vi-mode

[git_branch]
symbol = " "
style = "bold mauve"
format = "[$symbol$branch]($style) "

[git_status]
conflicted = '[ $count ](green)'
ahead = '[ $count ](green)'
behind = '[ $count ](yellow)'
diverged = '[$count ](yellow)'
up_to_date = '✓'
untracked = '[󱀶 $count ](orange)'
stashed = '[󱎤$count ](green)'
modified = '[ $count ](blue)'
staged = '[ $count ](green)'
renamed = '[ $count ](orange)'
deleted = '[ $count](red)'
format='[$conflict$ahead$behind$diverged$up_to_date$untracked$stashed$modified$staged$renamed$deleted]($format)'

[directory]
truncation_length = 0
truncation_symbol = "../"
style = "bold lavender"
read_only = " 󰌾"

[os]
disabled = false
style = "green"
format = "[$symbol]($style)"

[time]
disabled = false
format = '[\[$time\]](subtext0)'
time_format = '%T'
utc_time_offset = '+9'

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
