if [[ -o interactive ]] && [ -s "$HOME/.bun/_bun" ]; then
  source "$HOME/.bun/_bun"
fi

if [ -s "$HOME/.vite-plus/env" ]; then
  source "$HOME/.vite-plus/env"
fi

# Generated by Home Manager when Nix tooling is enabled.
[ -f "$HOME/.config/zsh/nix-env.zsh" ] && source "$HOME/.config/zsh/nix-env.zsh"
