name: Home Manager Activation Build Test

on:
  push:
    branches:
      - main
      - mise
    paths:
      - "config/home-manager/**"
      - "config/nix/**"
      - ".github/workflows/home-manager-test.yml"
  pull_request:
    paths:
      - "config/home-manager/**"
      - "config/nix/**"
      - ".github/workflows/home-manager-test.yml"
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: hal-macos
            os: macos-latest
            target: .#homeConfigurations."hal@MacBook-Pro.local".activationPackage
          - name: ci-linux
            os: ubuntu-latest
            target: .#homeConfigurations."ci@actions".activationPackage
    defaults:
      run:
        working-directory: config/home-manager
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6

      - uses: nixbuild/nix-quick-install-action@v34

      - name: Build Home Manager activation package
        run: nix build '${{ matrix.target }}'
